# Generated by Django 2.0 on 2017-12-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.TextField()),
                ('game_rom', models.TextField()),
            ],
        ),
    ]
